title: Luiz Desuó Neto
logo: https://avatars.githubusercontent.com/u/31017169?s=400&u=164e8561523f370a5dbf7def7bc03fec73b77879&v=4
description: PhD candidate
show_downloads: true
theme: jekyll-theme-minimal